C$TEST ERR3
C TO RUN AS A MAIN PROGRAM REMOVE NEXT LINE
      SUBROUTINE ERR3
C **********************************************************************
C
C  TO TEST THE ERROR HANDLING PACKAGE
C TEST NUMBER 3: TWO RECOVERABLE ERRORS IN A ROW.
C
C **********************************************************************
      INTEGER OLDREC, I1MACH
      INTEGER TEMP
C ENTER RECOVERY MODE.
      CALL ENTSRC(OLDREC, 1)
C/6S
      CALL SETERR(30HMAIN - FIRST RECOVERABLE ERROR, 30, 1, 1)
      CALL SETERR(31HMAIN - SECOND RECOVERABLE ERROR, 31, 2, 1)
C/7S
C     CALL SETERR('MAIN - FIRST RECOVERABLE ERROR', 30, 1, 1)
C     CALL SETERR('MAIN - SECOND RECOVERABLE ERROR', 31, 2, 1)
C/
      TEMP = I1MACH(2)
      WRITE (TEMP,  1)
   1  FORMAT (
     1   56H TWO RECOVERABLE ERRORS IN A ROW FAIL TO HALT EXECUTION.)
      STOP
      END
