#define error1 "\n*\tERROR[1]: Unknown option in XML for selection algorithm."
#define error2 "\n*\tERROR[2]: Unknown option in XML for replace algorithm."
#define error3 "\n*\tERROR[3]: Unknown option in XML for mutation strategy."
#define error4 "\n*\tERROR[4]: Unknown option in XML for parallel topology."
#define error5 "\n*\tERROR[5]: Unknown option in XML for parallel parametters strategy."
#define error6 "\n*\tERROR[6]: Processor population matrix has an inadequate size. Remember: Proc matrix population = (NP / NPROC)."
#define error7 "\n*\tERROR[7]: The program is implemented with more than one processor, but the program is configured for sequential execution."
#define error8 "\n*\tERROR[8]: There was an error in the execution of the solver."
#define error9 "\n*\tERROR[9]: Unknown option in XML for parallelization kind."
#define error10 "\n*\tERROR[10]: Unknown benchmark in XML."
#define error11 "\n*\tERROR[11]: N2sol benchmark is specific for System Biology problems"
#define error12 "\n*\tERROR[12]: Unknown global solver in XML"
#define error13 "\n*\tERROR[13]: Unknown local solver in XML"
#define error14 "\n*\tERROR[14]: Incorrect ID in Systems Biology problem."
#define error15 "\n*\tERROR[15]: Incorrect ID in noiselessBBOB benchmark. Range of ID 1-24"
#define error16 "\n*\tERROR[16]: Incorrect ID in noiseBBOB benchmark. Range of ID 101-130"
#define error17 "\n*\tERROR[17]: typebench field must appear in XML input file"
#define error18 "\n*\tERROR[18]: id field must appear in XML input file"
#define error19 "\n*\tERROR[19]: evaluation field must appear in XML input file"
#define error20 "\n*\tERROR[20]: log_scale field must appear in XML input file"
#define error21 "\n*\tERROR[21]: output field must appear in XML input file"
#define error22 "\n*\tERROR[22]: verbose field must appear in XML input file"
#define error23 "\n*\tERROR[23]: local_search field must appear in XML input file"
#define error24 "\n*\tERROR[24]: ineq field must appear in XML input file"
#define error25 "\n*\tERROR[25]: int_var field must appear in XML input file"
#define error26 "\n*\tERROR[26]: bin_var field must appear in XML input file"
#define error27 "\n*\tERROR[27]: parallelization field must appear in XML input file"
#define error28 "\n*\tERROR[28]: run field must appear in XML input file"
#define error29 "\n*\tERROR[29]: method field must appear in XML input file"
#define error30 "\n*\tERROR[30]: VTR field must appear in XML input file"
#define error31 "\n*\tERROR[31]: Not run sequential eSS with MPI!"
#define error32 "\n*\tERROR[32]: Use MPI with this solver!"
#define error33 "\n*\tERROR[33]: Use -DOPENMP flag in the compilation!"
#define error34 "\n*\tERROR[34]: problem field must appear in XML input file"
#define error35 "\n*\tERROR[35]: dim field must appear in metadata problem in the XML input file"
#define error36 "\n*\tERROR[36]: upper bounds have to be defined in XML"
#define error37 "\n*\tERROR[37]: number of bounds != dimension of the problem"
#define error38 "\n*\tERROR[38]: bounds are not defined"
#define error39 "\n*\tERROR[39]: saCeSS method needs more than 1 processor to work"
#define error40 "\n*\tERROR[40]: CeSS method needs more than 1 processor to work"
#define error41 "\n*\tERROR[41]: nl2sol local solver only can applied to problems created through AMIGO toolbox."
#define error42 "\n*\tERROR[42]: stopping_criteria field does not appears in XML."
#define error43 "\n*\tERROR[43]: matlab problems are only compatible with GNU compilers."

