name: ci

on:
  push:

env:
  stan_ver: 2.28.2

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: cmdstan

      - run: docker run --rm -v $PWD:/build -w /build cmdstan scl enable devtoolset-10 "make -C /work/cmdstan-$stan_ver $PWD/Stan/BVEP_seeg_noncentered_reparam"

      - uses: actions/upload-artifact@v2
        with:
          name: bvep
          path: Stan/BVEP_seeg_noncentered_reparam
