.TH "src/method_module/ Directory Reference" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/method_module/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBeSS\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommon_solver_operations\&.c\fP"
.br
.RI "\fIFile containing a set of functions with different purposes: arithmetic operations, management of random numbers, geometrical operations, search algorithms\&. \fP"
.ti -1c
.RI "file \fBcommon_solver_operations\&.d\fP"
.br
.ti -1c
.RI "file \fBevaluationinterface\&.c\fP"
.br
.RI "\fIFile containing functions about the evaluation of objective function\&. \fP"
.ti -1c
.RI "file \fBevaluationinterface\&.d\fP"
.br
.ti -1c
.RI "file \fBexecution_methods\&.d\fP"
.br
.ti -1c
.RI "file \fBparallel_functions\&.c\fP"
.br
.RI "\fIFile containing general functions about the parallelization of the algorithms with MPI\&. \fP"
.ti -1c
.RI "file \fBparallel_functions\&.d\fP"
.br
.ti -1c
.RI "file \fBsolversinterface\&.c\fP"
.br
.ti -1c
.RI "file \fBsolversinterface\&.d\fP"
.br
.ti -1c
.RI "file \fBstructure_paralleltestbed\&.c\fP"
.br
.RI "\fIFile containing setter and getter for all fields of the main struct \fBexperiment_total\fP\&. \fP"
.ti -1c
.RI "file \fBstructure_paralleltestbed\&.d\fP"
.br
.in -1c
