.TH "src/input_module/ Directory Reference" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/input_module/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinput_AMIGO\&.c\fP"
.br
.ti -1c
.RI "file \fBinput_AMIGO\&.d\fP"
.br
.ti -1c
.RI "file \fBinput_module\&.c\fP"
.br
.RI "\fIFile containing functions to parse the input XML, completing the main struct of \fBexperiment_total\fP data\&. \fP"
.ti -1c
.RI "file \fBinput_module\&.d\fP"
.br
.in -1c
