.TH "src/method_module/eSS/ Directory Reference" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/method_module/eSS/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlocalsolvers_eSS\&.c\fP"
.br
.RI "\fIFile containing function interfaces to use N2SOL local solver with eSS\&. \fP"
.ti -1c
.RI "file \fBlocalsolvers_eSS\&.d\fP"
.br
.ti -1c
.RI "file \fBparallel_functions_cooperative_eSS\&.c\fP"
.br
.RI "\fIFile containing specific function for the parallelization of the eSS\&. \fP"
.ti -1c
.RI "file \fBparallel_functions_cooperative_eSS\&.d\fP"
.br
.in -1c
