.TH "src/ Directory Reference" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinput_module\fP"
.br
.ti -1c
.RI "directory \fBmethod_module\fP"
.br
.ti -1c
.RI "directory \fBmethod_module_fortran\fP"
.br
.ti -1c
.RI "directory \fBoutput\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain_file\&.c\fP"
.br
.RI "\fIThis is the main file of the program\&. \fP"
.ti -1c
.RI "file \fBmain_file\&.d\fP"
.br
.ti -1c
.RI "file \fBsetup_benchmarks\&.c\fP"
.br
.RI "\fIFile containing functions about the load for different benchmarks\&. When users typical want to put their benchmarks, they should modify this file\&. \fP"
.ti -1c
.RI "file \fBsetup_benchmarks\&.d\fP"
.br
.in -1c
