.TH "src/output/ Directory Reference" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/output/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBoutput\&.c\fP"
.br
.RI "\fIFile containing all functions about the different outputs of the program: print screens, files logs, matlab files generation etc\&. \fP"
.ti -1c
.RI "file \fBoutput\&.d\fP"
.br
.ti -1c
.RI "file \fBread_a_file_line_by_line\&.c\fP"
.br
.ti -1c
.RI "file \fBread_a_file_line_by_line\&.d\fP"
.br
.in -1c
