.TH "dhc_mod" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dhc_mod \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBinsert_in_bounds\fP (xv)"
.br
.ti -1c
.RI "subroutine \fBcheck_bounds\fP (xvreal, XL, XU, pen2)"
.br
.ti -1c
.RI "subroutine \fBdhc\fP (problem1, exp1, opts1, fitnessfunction, X0, initsize, thres, budget, numeval, fx)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file dhc\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
