.TH "execution_vars" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
execution_vars \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBnameMatlab\fP"
.br
.ti -1c
.RI "\fBtopology_data\fP \fBtopology\fP"
.br
.ti -1c
.RI "int \fBsize_send_buffer\fP"
.br
.ti -1c
.RI "int \fBsend_id\fP"
.br
.ti -1c
.RI "int * \fBst\fP"
.br
.ti -1c
.RI "int \fBidp\fP"
.br
.ti -1c
.RI "int \fBnum_it\fP"
.br
.ti -1c
.RI "double \fBmax_time_ite\fP"
.br
.ti -1c
.RI "double \fBmax_time_ite_last\fP"
.br
.ti -1c
.RI "int \fBNPROC\fP"
.br
.ti -1c
.RI "int \fBtam\fP"
.br
.ti -1c
.RI "int \fBNP\fP"
.br
.ti -1c
.RI "int \fBNM\fP"
.br
.ti -1c
.RI "int \fBst_sent\fP"
.br
.ti -1c
.RI "int \fBstuckcond_lowVar\fP"
.br
.ti -1c
.RI "int \fBstuckcount\fP"
.br
.ti -1c
.RI "int \fBmigra_asin_wait\fP"
.br
.ti -1c
.RI "int \fBmigration\fP"
.br
.ti -1c
.RI "int \fBcontadorMigra\fP"
.br
.ti -1c
.RI "int \fBenterMigrat\fP"
.br
.ti -1c
.RI "int \fBupdate\fP"
.br
.ti -1c
.RI "int \fBmax_eval_ite_last\fP"
.br
.ti -1c
.RI "double \fBminvarcondition\fP"
.br
.ti -1c
.RI "double \fBftarget\fP"
.br
.ti -1c
.RI "long \fBmaxfunevals\fP"
.br
.ti -1c
.RI "double \fBinitTIME\fP"
.br
.ti -1c
.RI "int \fBrep\fP"
.br
.ti -1c
.RI "int \fBinitpath\fP"
.br
.ti -1c
.RI "int \fBiteration\fP"
.br
.ti -1c
.RI "double * \fBtransconst\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "long \fBfailevals\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 204 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
