.TH "line_reader" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
line_reader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FILE * \fBf\fP"
.br
.ti -1c
.RI "char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBsiz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file read_a_file_line_by_line\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
