.TH "local_options" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local_options \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtol\fP"
.br
.ti -1c
.RI "int \fBiterprint\fP"
.br
.ti -1c
.RI "int \fBn1\fP"
.br
.ti -1c
.RI "int \fBn2\fP"
.br
.ti -1c
.RI "double \fBbalance\fP"
.br
.ti -1c
.RI "char * \fBsolver\fP"
.br
.ti -1c
.RI "char * \fBfinish\fP"
.br
.ti -1c
.RI "int \fBbestx\fP"
.br
.ti -1c
.RI "int \fBmerit_filter\fP"
.br
.ti -1c
.RI "int \fBdistance_filter\fP"
.br
.ti -1c
.RI "double \fBthfactor\fP"
.br
.ti -1c
.RI "double \fBmaxdistfactor\fP"
.br
.ti -1c
.RI "int \fBwait_maxdist_limit\fP"
.br
.ti -1c
.RI "int \fBwait_th_limit\fP"
.br
.ti -1c
.RI "long \fBevalmax\fP"
.br
.ti -1c
.RI "\fBextraparametters\fP \fBextrap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
