.TH "src/main_file.c" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main_file.c \- 
.PP
This is the main file of the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <configuration\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <structure_paralleltestbed\&.h>\fP
.br
\fC#include <input_module\&.h>\fP
.br
\fC#include <output\&.h>\fP
.br
\fC#include <example\&.h>\fP
.br
\fC#include <setup_benchmarks\&.h>\fP
.br
\fC#include <def_errors\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the main file of the program\&. 

\fBAuthor:\fP
.RS 4
David R\&. Penas 
.RE
.PP

.PP
Definition in file \fBmain_file\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
