.TH "misqp_interface" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
misqp_interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBevaluate_gradient\fP (problem1, exp1, opts1, x, f, g, ncont, nfunc, m, df, dg, fobj_mysqp, pass_misqp, neq, fitnessfunction)"
.br
.ti -1c
.RI "subroutine \fBevaluate_gradient_parallel\fP (problem1, exp1, opts1, x, f, g, ncont, nfunc, m, df, dg, fobj_mysqp, pass_misqp, neq, fitnessfunction)"
.br
.ti -1c
.RI "subroutine \fBfobj_misqp\fP (fitnessfunction, exp1, x, g, neq, local_solver_vars, problem1)"
.br
.ti -1c
.RI "subroutine \fBssm_aux_local_misqp\fP (problem1, local_solver_vars)"
.br
.ti -1c
.RI "subroutine \fBrun_misqp\fP (problem1, exp1, opts1, fitnessfunction, acc, x0, fval, nfunc, ifail, g, local_solver_vars)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file misqp_interface\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
