.TH "output_struct" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBst1\fP"
.br
.ti -1c
.RI "double \fBst2\fP"
.br
.ti -1c
.RI "double \fBst3\fP"
.br
.ti -1c
.RI "double \fBpoint1\fP"
.br
.ti -1c
.RI "int \fBpoint_counter\fP"
.br
.ti -1c
.RI "double \fBoldbest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 274 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
