.TH "output_function" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
output_function \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "double * \fBg\fP"
.br
.ti -1c
.RI "double * \fBR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 324 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
