.TH "src/method_module/eSS/parallel_functions_cooperative_eSS.c" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/method_module/eSS/parallel_functions_cooperative_eSS.c \- 
.PP
File containing specific function for the parallelization of the eSS\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
File containing specific function for the parallelization of the eSS\&. 

\fBAuthor:\fP
.RS 4
David R\&. Penas 
.RE
.PP

.PP
Definition in file \fBparallel_functions_cooperative_eSS\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
