.TH "parallelization_strategy" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parallelization_strategy \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBNPROC\fP"
.br
.ti -1c
.RI "int \fBNPROC_OPENMP\fP"
.br
.ti -1c
.RI "int \fBmigration_size\fP"
.br
.ti -1c
.RI "int \fBmigration_freq_ite\fP"
.br
.ti -1c
.RI "double \fBmax_time_ite\fP"
.br
.ti -1c
.RI "const char * \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBcommu\fP"
.br
.ti -1c
.RI "const char * \fBislandstrategy\fP"
.br
.ti -1c
.RI "const char * \fBtopology\fP"
.br
.ti -1c
.RI "const char * \fBSelectionPolicy\fP"
.br
.ti -1c
.RI "const char * \fBReplacePolicy\fP"
.br
.ti -1c
.RI "int \fBevals_threshold\fP"
.br
.ti -1c
.RI "int \fBmult_num_sendSol\fP"
.br
.ti -1c
.RI "int \fBminimum_num_sendSol\fP"
.br
.ti -1c
.RI "int \fBreception_threshold\fP"
.br
.ti -1c
.RI "double \fBmax_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 183 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
