.TH "src/method_module/parallel_functions.c" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/method_module/parallel_functions.c \- 
.PP
File containing general functions about the parallelization of the algorithms with MPI\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
File containing general functions about the parallelization of the algorithms with MPI\&. 

\fBAuthor:\fP
.RS 4
David R\&. Penas 
.RE
.PP

.PP
Definition in file \fBparallel_functions\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
