.TH "scattersearchtypes" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "type \fBadapt_vars\fP"
.br
.ti -1c
.RI "type \fBalgorithm_common_vars\fP"
.br
.ti -1c
.RI "type \fBess_common_vars\fP"
.br
.ti -1c
.RI "type \fBextraparametters\fP"
.br
.ti -1c
.RI "type \fBgoptions\fP"
.br
.ti -1c
.RI "type \fBlocal_solver_help_vars\fP"
.br
.ti -1c
.RI "type \fBloptions\fP"
.br
.ti -1c
.RI "type \fBmaster_migration\fP"
.br
.ti -1c
.RI "type \fBopts\fP"
.br
.ti -1c
.RI "type \fBoutfuction\fP"
.br
.ti -1c
.RI "type \fBproblem\fP"
.br
.ti -1c
.RI "type \fBrefsettype\fP"
.br
.ti -1c
.RI "type \fBresultsf\fP"
.br
.ti -1c
.RI "type \fBtime_ess\fP"
.br
.ti -1c
.RI "type \fBtopology_data_fortran\fP"
.br
.ti -1c
.RI "type \fBuoptions\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer, parameter \fBprecision_d\fP = 15"
.br
.ti -1c
.RI "integer, parameter \fBrange_d\fP = 307"
.br
.ti -1c
.RI "integer, parameter \fBprecision_f\fP = 7"
.br
.ti -1c
.RI "integer, parameter \fBrange_f\fP = 150"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), parameter \fBtol_prec\fP = REAL(1d-18, KIND=SELECTED_REAL_KIND(P=PRECISION_D, R=RANGE_D))"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), parameter \fBeps_m\fP = REAL(1d-18, KIND=SELECTED_REAL_KIND(P=PRECISION_D, R=RANGE_D))"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), parameter \fBauxprecisin\fP = REAL(10000d0, KIND=SELECTED_REAL_KIND(P=PRECISION_D, R=RANGE_D))"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), parameter \fBinfinite\fP = 1\&.7976931348623158D308"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
