.TH "scattersearchtypes::master_migration" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::master_migration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer(c_int), dimension(:), 
.br
allocatable \fBvector_proc\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBocurrences_send\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
