.TH "scattersearchtypes::uoptions" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::uoptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBempty\fP"
.br
.ti -1c
.RI "integer \fBiterprint\fP"
.br
.ti -1c
.RI "integer \fBplot\fP"
.br
.ti -1c
.RI "integer \fBweight\fP"
.br
.ti -1c
.RI "integer \fBnstuck_solution\fP"
.br
.ti -1c
.RI "integer \fBstrategy\fP"
.br
.ti -1c
.RI "integer \fBinter_save\fP"
.br
.ti -1c
.RI "integer(c_long_long) \fBmaxeval\fP"
.br
.ti -1c
.RI "real(c_double) \fBmaxtime\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBtolc\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBprob_bound\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBlog_var\fP"
.br
.ti -1c
.RI "integer \fBinit_point\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 96 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
