.TH "scattersearchtypes::adapt_vars" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::adapt_vars \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBsize_dim_pen\fP"
.br
.ti -1c
.RI "integer \fBncounter_pen\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBbalance_pen\fP"
.br
.ti -1c
.RI "integer \fBpending\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
