.TH "scattersearchtypes::problem" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::problem \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBempty\fP"
.br
.ti -1c
.RI "character(len=20) \fBf\fP"
.br
.ti -1c
.RI "integer \fBneq\fP"
.br
.ti -1c
.RI "integer \fBint_var\fP"
.br
.ti -1c
.RI "integer \fBbin_var\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBvtr\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBxl\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBxu\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBcl\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBcu\fP"
.br
.ti -1c
.RI "integer \fBineq\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:,:), 
.br
allocatable \fBx0\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBf0\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
