.TH "scattersearchtypes::algorithm_common_vars" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::algorithm_common_vars \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBnproc\fP"
.br
.ti -1c
.RI "integer \fBidp\fP"
.br
.ti -1c
.RI "integer \fBparallel\fP"
.br
.ti -1c
.RI "integer \fBcooperative\fP"
.br
.ti -1c
.RI "integer \fBinititer\fP"
.br
.ti -1c
.RI "integer \fBinit_comm\fP"
.br
.ti -1c
.RI "integer \fBsizeser\fP"
.br
.ti -1c
.RI "integer \fBiter\fP"
.br
.ti -1c
.RI "integer \fBstatus\fP"
.br
.ti -1c
.RI "integer \fBnvar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
