.TH "scattersearchtypes::topology_data_fortran" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::topology_data_fortran \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBnum_r\fP"
.br
.ti -1c
.RI "integer \fBnum_left\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBrigth\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBleft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
