.TH "scattersearchtypes::loptions" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::loptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBempty\fP"
.br
.ti -1c
.RI "integer \fBtol\fP"
.br
.ti -1c
.RI "integer \fBiterprint\fP"
.br
.ti -1c
.RI "integer \fBn1\fP"
.br
.ti -1c
.RI "integer \fBn2\fP"
.br
.ti -1c
.RI "integer \fBbestx\fP"
.br
.ti -1c
.RI "integer \fBmerit_filter\fP"
.br
.ti -1c
.RI "integer \fBdistance_filter\fP"
.br
.ti -1c
.RI "integer \fBwait_maxdist_limit\fP"
.br
.ti -1c
.RI "integer \fBwait_th_limit\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBthreshold_local\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBthfactor\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBmaxdistfactor\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBbalance\fP"
.br
.ti -1c
.RI "type(\fBextraparametters\fP) \fBextrap\fP"
.br
.ti -1c
.RI "character(len=20, kind=c_char) \fBsolver\fP"
.br
.ti -1c
.RI "character(len=20, kind=c_char), 
.br
dimension(:), allocatable \fBfinish\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 137 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
