.TH "scattersearchtypes::time_ess" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::time_ess \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real(c_double) \fBtimeparallel\fP"
.br
.ti -1c
.RI "real(c_double) \fBlocalsolvertime\fP"
.br
.ti -1c
.RI "real(c_double) \fBstarttime\fP"
.br
.ti -1c
.RI "integer \fBclock_rate\fP"
.br
.ti -1c
.RI "integer \fBclock_start\fP"
.br
.ti -1c
.RI "integer \fBclock_stop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
