.TH "scattersearchtypes::goptions" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::goptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "integer \fBempty\fP"
.br
.ti -1c
.RI "integer \fBdim_refset\fP"
.br
.ti -1c
.RI "integer \fBndiverse\fP"
.br
.ti -1c
.RI "integer \fBinitiate\fP"
.br
.ti -1c
.RI "integer \fBcombination\fP"
.br
.ti -1c
.RI "integer \fBregenerate\fP"
.br
.ti -1c
.RI "integer \fBintens\fP"
.br
.ti -1c
.RI "integer \fBdiverse_criteria\fP"
.br
.ti -1c
.RI "integer \fBn_stuck\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBtolf\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)) \fBtolx\fP"
.br
.ti -1c
.RI "character(len=20, kind=c_char) \fBdelete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
