.TH "scattersearchtypes::refsettype" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchtypes::refsettype \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:,:), 
.br
allocatable \fBx\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBf\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBfpen\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:,:), 
.br
allocatable \fBnlc\fP"
.br
.ti -1c
.RI "real(kind=selected_real_kind(p=precision_d, 
.br
r=range_d)), dimension(:), 
.br
allocatable \fBpenalty\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBparent_index\fP"
.br
.ti -1c
.RI "integer, dimension(:), allocatable \fBcooperative\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file scattersearchtypes\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
