.TH "scattersearchfunctions" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
scattersearchfunctions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "subroutine \fBproblem_specifications\fP (exp1, problem1, opts1, nvar, ftarget, maxfunevals)"
.br
.ti -1c
.RI "subroutine \fBdestroy_problem\fP (problem1)"
.br
.ti -1c
.RI "subroutine \fBdestroy_opts\fP (opts1)"
.br
.ti -1c
.RI "TYPE(opts) function \fBssm_default\fP ()"
.br
.ti -1c
.RI "subroutine \fBcreate_new_opts\fP (opts1)"
.br
.ti -1c
.RI "subroutine \fBcreate_new_problem\fP (problem1)"
.br
.ti -1c
.RI "TYPE(opts) function \fBssm_optset\fP (default1, opts1)"
.br
.ti -1c
.RI "subroutine \fBprint_opts\fP (opts1)"
.br
.ti -1c
.RI "subroutine \fBprint_problems\fP (problem1)"
.br
.ti -1c
.RI "subroutine \fBlog_vector\fP (vector)"
.br
.ti -1c
.RI "subroutine \fBssm_beyond\fP (exp1, z1, z2, z2_val, nfuneval, fitnessfunction, nrand, nconst, outfunction, opts1, problem1, idopenmp)"
.br
.ti -1c
.RI "subroutine \fBssm_beyond_det\fP (exp1, z1, z2, z2_val, nfuneval, fitnessfunction, nrand, nconst, outfunction, opts1, problem1, idopenmp, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBcreate_init_solutions\fP (exp1, opts1, solutions, nvar, xl_log, xu_log)"
.br
.ti -1c
.RI "subroutine \fBcreate_init_solutions_det\fP (exp1, opts1, solutions, nvar, xl_log, xu_log, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBinit_inequality_constraints\fP (neq, c_L, c_U)"
.br
.ti -1c
.RI "subroutine \fBcalc_dim_refset\fP (dim_refset, nvar, iterprint, idp, NPROC)"
.br
.ti -1c
.RI "subroutine \fBcalc_ndiverse\fP (ndiverse, nvar, iterprint, idp)"
.br
.ti -1c
.RI "subroutine \fBdestroy_refsettype\fP (refset)"
.br
.ti -1c
.RI "subroutine \fBdestroy_resultsf\fP (results)"
.br
.ti -1c
.RI "subroutine \fBevaluate_solutions_set\fP (exp1, fitnessfunction, solutionset, problem1, opts1, solutions, nvar, nfuneval, nconst, xl_log, xu_log)"
.br
.ti -1c
.RI "subroutine \fBcreate_refset\fP (exp1, solutionset, refset, nvar, opts1, nconst, dim_refset)"
.br
.ti -1c
.RI "subroutine \fBcreate_refset_empty\fP (refset, nvar, opts1, nconst, size)"
.br
.ti -1c
.RI "subroutine \fBcreate_refset_det\fP (solutionset, refset, nvar, opts1, nconst, dim_refset)"
.br
.ti -1c
.RI "subroutine \fBcreate_childset\fP (childset, nvar, MaxSubSet2, nconst)"
.br
.ti -1c
.RI "subroutine \fBcheck_best_value\fP (refset, opts1, xbest, fbest)"
.br
.ti -1c
.RI "subroutine \fBcreate_results\fP (results, opts1, xbest, fbest, nfuneval, cputime1, nvar)"
.br
.ti -1c
.RI "subroutine \fBsort_refset\fP (refset, opts1, indvect)"
.br
.ti -1c
.RI "subroutine \fBcreate_candidate\fP (candidateset, refset)"
.br
.ti -1c
.RI "subroutine \fBcheck_duplicated_replace\fP (exp1, fitnessfunction, problem1, refset, opts1, parents_index1, parents_index2, xl_log, xu_log, refset_change, members_update, index1, index2, nfuneval, nvar, nconst)"
.br
.ti -1c
.RI "subroutine \fBcheck_duplicated_replace_det\fP (exp1, fitnessfunction, problem1, refset, opts1, parents_index1, parents_index2, xl_log, xu_log, refset_change, members_update, index1, index2, nfuneval, nvar, nconst, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBcheck_vector_in_hyper_bounds\fP (exp1, opts1, v, hyper_x_L, hyper_x_U)"
.br
.ti -1c
.RI "subroutine \fBcheck_vector_in_hyper_bounds_det\fP (exp1, opts1, v, hyper_x_L, hyper_x_U, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBgenerate_new_comb_matrix\fP (exp1, new_comb, ppp, MaxSubSet, nrand, v1, v2, v3)"
.br
.ti -1c
.RI "subroutine \fBgenerate_new_comb_matrix_det\fP (exp1, new_comb, ppp, MaxSubSet, nrand, v1, v2, v3, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBupdate_candidateset_with_new_comb\fP (exp1, opts1, fitnessfunction, problem1, new_comb, candidateset, childset, candidate_update, members_update, MaxSubSet2, nrand, nconst, nfuneval, counter, index)"
.br
.ti -1c
.RI "integer function \fBcheck_stopping_criteria\fP (problem1, opts1, cputime, stopOptimization, fbest, nfuneval)"
.br
.ti -1c
.RI "subroutine \fBselect_better_solution\fP (results, opts1, refset, xbest, fbest, use_bestx, nfuneval, time, fin)"
.br
.ti -1c
.RI "subroutine \fBupdate_refset_change\fP (members_update, refset_change)"
.br
.ti -1c
.RI "subroutine \fBremove_possible_stuck_members_in_refset\fP (problem1, opts1, exp1, fitnessfunction, nconst, refset, refset_change, nfuneval, nvar, xl_log, xu_log)"
.br
.ti -1c
.RI "subroutine \fBremove_possible_stuck_members_in_refset_det\fP (problem1, opts1, exp1, fitnessfunction, nconst, refset, refset_change, nfuneval, nvar, xl_log, xu_log, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBcheck_the_improvement_of_fbest\fP (results, opts1, fbest, xbest, fbest_lastiter, nreset, cputime2, fin, nfuneval)"
.br
.ti -1c
.RI "subroutine \fBapply_beyond_to_members_to_update\fP (exp1, opts1, fitnessfunction, problem1, members_to_update, nfuneval, refset, candidateset, nconst, nrand, nvar)"
.br
.ti -1c
.RI "subroutine \fBapply_beyond_to_members_to_update_det\fP (exp1, opts1, fitnessfunction, problem1, members_to_update, nfuneval, refset, candidateset, nconst, nrand, nvar, contador, matrixR)"
.br
.ti -1c
.RI "subroutine \fBreajustchild\fP (childset, cont, nvar, nconst)"
.br
.ti -1c
.RI "subroutine \fBserializerefset\fP (refset, nvar, tam, servector, rest)"
.br
.ti -1c
.RI "subroutine \fBdeserializerefset\fP (refset, nvar, tam, servector)"
.br
.ti -1c
.RI "subroutine \fBsizeseriallize\fP (nvar, nconst, size)"
.br
.ti -1c
.RI "subroutine \fBcheckbounds\fP (problem1, st)"
.br
.ti -1c
.RI "subroutine \fBinitbestvars\fP (problem1, xbest, fbest, nvar)"
.br
.ti -1c
.RI "subroutine \fBinitintbinvars\fP (problem1)"
.br
.ti -1c
.RI "subroutine \fBinitlocaloptions\fP (opts1)"
.br
.ti -1c
.RI "subroutine \fBcalcnconst\fP (problem1, nconst)"
.br
.ti -1c
.RI "subroutine \fBcheck_output_obj_funct\fP (problem1, opts1, status, nconst)"
.br
.ti -1c
.RI "subroutine \fBfinalize_algorithm\fP (exp1, problem1, results, opts1, fitnessfunction, refset, xbest, fbest, fin, nfuneval, NPROC, cputime3, nconst, nvar, local_solver_var, idp)"
.br
.ti -1c
.RI "subroutine \fBcalc_indexes\fP (ncomb1, ncomb2, index1, index2, index, diff_index, auxsize)"
.br
.ti -1c
.RI "subroutine \fBcalc_ppp\fP (auxsize, ppp, dim_refset, diff_index)"
.br
.ti -1c
.RI "subroutine \fBcalc_hyper\fP (nvar, hyper_x_L, hyper_x_U, MaxSubSet, XU, XL)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file scattersearchfunctions\&.f90\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
