.TH "topology_data" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
topology_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBrigth\fP"
.br
.ti -1c
.RI "int \fBnum_r\fP"
.br
.ti -1c
.RI "int * \fBleft\fP"
.br
.ti -1c
.RI "int \fBnum_left\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
