.TH "user_options" 3 "Wed May 11 2016" "Version 0.1" "SACESS TOOLBOX" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_options \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBweight\fP"
.br
.ti -1c
.RI "double \fBtolc\fP"
.br
.ti -1c
.RI "double \fBprob_bound\fP"
.br
.ti -1c
.RI "int \fBnstuck_solution\fP"
.br
.ti -1c
.RI "int \fBstrategy\fP"
.br
.ti -1c
.RI "int \fBinter_save\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file structure_paralleltestbed\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SACESS TOOLBOX from the source code\&.
